sudo: required
services:
  - docker

before_install:
  - docker build -t yuryshkoda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yuryshkoda/react-test npm test -- --coverage

after_success:
  - docker build -t yuryshkoda/multi-client ./client
  - docker build -t yuryshkoda/multi-nginx ./nginx
  - docker build -t yuryshkoda/multi-server ./server
  - docker build -t yuryshkoda/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yuryshkoda/multi-client
  - docker push yuryshkoda/multi-nginx
  - docker push yuryshkoda/multi-server
  - docker push yuryshkoda/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-432610128422'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
